server:
  port: 8882
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Roram-io/config-data
          searchPaths: properties
          default-label: development
  security:
    user:
      name: admin
      password: nttdatacorazon
