server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://http://20.75.128.229:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/api/v1/customer/**
        - id: ms-credit
          uri: lb://ms-credit
          predicates:
            - Path=/api/v1/credit/**
        - id: ms-transaction
          uri: lb://ms-transaction
          predicates:
            - Path=/api/v1/transaction/**
        - id: ms-account
          uri: lb://ms-account
          predicates:
            - Path=/api/v1/account/**
        - id: ms-card
          uri: lb://ms-card
          predicates:
            - Path=/api/v1/card/**